# Writes session_info.txt: the version and source of every package this pipeline
# loads, so a committed result can be traced to the code that produced it.
#
# renv::dependencies() reads the scripts rather than the search path, so the record
# covers the whole pipeline instead of whatever one session happens to have attached.
# This deliberately stops short of renv::init(): no project library, no .Rprofile, so
# running it cannot break a working checkout. It records; it does not restore.
#
# Locally built packages report their source as "local". enrichVolcano is the one that
# matters here -- its version string does not change between commits, so the record is
# only as precise as the source line beside it. Reinstall it with
# remotes::install_github() and the record gains a resolvable SHA.
#
#   Rscript session_info.R

pacman::p_load(renv, sessioninfo, here)

pkgs <- sort(unique(renv::dependencies(here::here(), quiet = TRUE)$Package))
available <- pkgs[vapply(pkgs, requireNamespace, logical(1), quietly = TRUE)]

info <- sessioninfo::session_info(pkgs = available, dependencies = FALSE)
lines <- c(
  "Generated by session_info.R. Regenerate rather than edit.",
  "",
  capture.output(print(info))
)

missing <- setdiff(pkgs, available)
if (length(missing)) {
  lines <- c(lines, "", "Referenced but not installed:", paste(" ", missing))
}

writeLines(lines, here::here("session_info.txt"))
