# Figure 3 — Panel E (Supp): fGSEA Stacked Bar Chart (Pathway Enrichment) ----
#
# Dodged Up/Down bars per contrast, stacked by database.
# Stack order bottom->top (largest->smallest): GO:BP, Reactome, Hallmark, KEGG, GO Slim.
# Reads fGSEA cache generated by panel_D.R — run that first.
# Outputs: pE_combined (patchwork object), panel_E_fgsea_stacked_SUPP.pdf/.png

if (!exists("meta")) source("04_Figures/F03/a_script/HRvLR_F03_setup.R")

library(patchwork)

RPT <- RPT_DIR
DAT <- DAT_DIR

# Read fGSEA cache from panel_D ----

fgsea_cache <- file.path(DAT, "06_panel_D_fgsea_results.csv")
if (!file.exists(fgsea_cache)) {
  stop("Panel E requires fGSEA cache from panel_D. ",
       "Run panel_D.R first to generate: ", fgsea_cache)
}
fgsea_raw <- read_csv(fgsea_cache, show_col_types = FALSE)

# Stack order: largest DB at bottom (darkest) -> smallest at top (lightest)
DB_ORDER <- c("GO:BP", "Reactome", "Hallmark", "KEGG", "GO Slim")

DISPLAY_CONTRASTS <- c("Training_HR", "Training_LR", "Acute_HR",
                       "Acute_LR", "Baseline_HRvLR")

# --- Color gradients: darkest at bottom -> lightest at top ---

red_shades  <- colorRampPalette(c("#B2182B", "#D6604D", "#F4A582"))(length(DB_ORDER))
blue_shades <- colorRampPalette(c("#2166AC", "#4393C3", "#92C5DE"))(length(DB_ORDER))
names(red_shades)  <- DB_ORDER
names(blue_shades) <- DB_ORDER

# --- Count sig pathways per contrast x direction x database ---

count_df <- fgsea_raw |>
  filter(!is.na(padj), padj < 0.05,
         database %in% DB_ORDER, contrast %in% DISPLAY_CONTRASTS) |>
  mutate(direction = ifelse(NES > 0, "Up", "Down")) |>
  group_by(contrast, direction, database) |>
  summarise(count = n(), .groups = "drop")

# Fill missing combos with 0
full_grid <- expand_grid(
  contrast  = DISPLAY_CONTRASTS,
  direction = c("Up", "Down"),
  database  = DB_ORDER
)
count_df <- full_grid |>
  left_join(count_df, by = c("contrast", "direction", "database")) |>
  mutate(count = replace_na(count, 0))

count_df$database <- factor(count_df$database, levels = DB_ORDER)

# --- Manual x positions for dodged bars ---

BAR_W     <- 0.30
DODGE_GAP <- 0.08
ctr_centers <- setNames(seq_along(DISPLAY_CONTRASTS), DISPLAY_CONTRASTS)

count_df <- count_df |>
  mutate(
    x_center = ctr_centers[contrast] +
      ifelse(direction == "Up", -(BAR_W / 2 + DODGE_GAP / 2),
                                  BAR_W / 2 + DODGE_GAP / 2)
  )

# --- Compute cumulative y positions for stacking ---

count_df <- count_df |>
  arrange(contrast, direction, factor(database, levels = DB_ORDER)) |>
  group_by(contrast, direction) |>
  mutate(
    ymax = cumsum(count),
    ymin = ymax - count
  ) |>
  ungroup()

# Assign fill colors
count_df <- count_df |>
  mutate(fill = ifelse(direction == "Up",
                       red_shades[as.character(database)],
                       blue_shades[as.character(database)]))

# --- Bar-top totals ---

bar_tops <- count_df |>
  group_by(contrast, direction, x_center) |>
  summarise(total = sum(count), .groups = "drop")

# --- Plot dimensions ---

PE_W <- 170
PE_H <- 150
lbl_sz <- scale_text(BASE_COUNT, PE_W)

# --- Background rects ---

bg_rects <- tibble(
  xmin = seq_along(DISPLAY_CONTRASTS) - 0.5,
  xmax = seq_along(DISPLAY_CONTRASTS) + 0.5,
  fill = CONTRAST_COLORS[DISPLAY_CONTRASTS]
)

pE <- ggplot() +
  # Contrast background shading
  geom_rect(data = bg_rects,
            aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf),
            fill = bg_rects$fill, alpha = 0.20,
            color = "grey70", linewidth = 0.2) +
  # Stacked database segments
  geom_rect(data = count_df,
            aes(xmin = x_center - BAR_W / 2, xmax = x_center + BAR_W / 2,
                ymin = ymin, ymax = ymax),
            fill = count_df$fill, color = "white", linewidth = 0.25) +
  # Total count labels above bars
  geom_text(data = bar_tops |> filter(total > 0),
            aes(x = x_center, y = total, label = total),
            vjust = -0.3, size = lbl_sz + 0.2, fontface = "bold",
            color = "grey20") +
  scale_x_continuous(
    breaks = seq_along(DISPLAY_CONTRASTS),
    labels = CTR_SHORT[DISPLAY_CONTRASTS],
    expand = expansion(mult = 0.05)
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +
  coord_cartesian(clip = "off") +
  labs(title = "Pathways Enriched Up/Down",
       subtitle = sprintf(
         "fGSEA | %s | per-database BH | %d sig / %d tested",
         paste(DB_ORDER, collapse = " + "),
         sum(count_df$count),
         nrow(fgsea_raw |> filter(database %in% DB_ORDER,
                                  contrast %in% DISPLAY_CONTRASTS))),
       x = NULL, y = "Significant pathways (padj < 0.05)",
       tag = "E") +
  FIG_THEME +
  theme(
    axis.text.x        = element_text(angle = 35, hjust = 1,
                                      size = FIG_AXIS_TEXT - 0.5),
    legend.position    = "none",
    panel.grid.major.x = element_blank(),
    plot.margin        = margin(5, 8, 2, 5)
  )

# --- Legend: horizontal layout below the plot ---

key_sq_sz <- 2.5
key_txt   <- lbl_sz - 0.8

grey_shades <- colorRampPalette(c("grey30", "grey75"))(length(DB_ORDER))
names(grey_shades) <- DB_ORDER

key_df <- tibble(
  label = c("Up", "Down", DB_ORDER),
  fill  = c(unname(DIR_COLORS[c("Up", "Down")]),
            grey_shades[DB_ORDER]),
  x     = seq_along(c("Up", "Down", DB_ORDER)),
  section = c("Direction", "Direction",
              rep("Database", length(DB_ORDER)))
)

pE_key <- ggplot(key_df) +
  geom_point(aes(x = x, y = 0), shape = 22, size = key_sq_sz,
             fill = key_df$fill, color = "grey30", stroke = 0.4) +
  geom_text(aes(x = x, y = -0.4, label = label),
            size = key_txt, color = "grey20") +
  annotate("text", x = 1.5, y = 0.6, label = "Direction",
           size = key_txt, fontface = "bold", color = "grey20") +
  annotate("text", x = mean(seq(3, 2 + length(DB_ORDER))), y = 0.6,
           label = "Database",
           size = key_txt, fontface = "bold", color = "grey20") +
  scale_y_continuous(limits = c(-1, 1)) +
  theme_void() +
  theme(plot.margin = margin(0, 2, 2, 2))

pE_combined <- pE / pE_key + plot_layout(heights = c(6, 1))

save_panel(pE_combined, file.path(RPT, "supp", "panel_E_fgsea_stacked_SUPP"),
           PE_W, PE_H)
message("F03 Panel E (fGSEA stacked bar, supp) done.")
